# Generated by Django 4.1.7 on 2023-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=400)),
                ('tax_number', models.IntegerField()),
                ('address_line_one', models.CharField(blank=True, max_length=400, null=True)),
                ('address_line_two', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(blank=True, max_length=400, null=True)),
                ('state', models.CharField(blank=True, max_length=400, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=400, null=True)),
                ('country', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
