# Generated by Django 4.1.7 on 2023-03-29 10:24

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(upload_to=accounts.models.user.image_directory_path),
        ),
    ]
