# Generated by Django 4.2.1 on 2023-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='tax_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
