# Generated by Django 4.1.7 on 2023-03-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_country',
            field=models.CharField(max_length=255),
        ),
    ]
