# Generated by Django 4.2.1 on 2023-05-18 11:18

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companydetails_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=accounts.models.user.image_directory_path),
        ),
    ]
