version: '3.9'

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: talent-db-pwd
      POSTGRES_USER: talent-db-user
      POSTGRES_DB: talent-db-name
  talent:
    build:
      context: .
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: 'secret-key'
      DJANGO_SETTINGS_MODULE: core.settings.development
      POSTGRES_DB: talent-db-name
      POSTGRES_USER: talent-db-user
      POSTGRES_PASSWORD: talent-db-pwd
      POSTGRES_IP: db
      PORT: 8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      REDIS_BACKEND: 'redis://redis:6379'
    env_file:
      - .env
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - ./app/:/usr/src/app/
    environment:
      POSTGRES_DB: talent-db-name
      POSTGRES_USER: talent-db-user
      POSTGRES_PASSWORD: talent-db-pwd
      POSTGRES_IP: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      REDIS_BACKEND: 'redis://redis:6379'
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - talent
volumes:
  redis:
    driver: local
  postgres_data:
