version: '3.7'

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      dockerfile: Dockerfile.prod
***REMOVED***
***REMOVED***
***REMOVED***
      - 8500:8500
***REMOVED***
***REMOVED***
      DJANGO_SETTINGS_MODULE: core.settings.production
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      PORT: 8500
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***