version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: talent-db-pwd
      POSTGRES_USER: talent-db-user
      POSTGRES_DB: talent-db-name
  talent:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8500:8500
    environment:
      SECRET_KEY: 'secret-key'
      DJANGO_SETTINGS_MODULE: core.settings.production
      POSTGRES_DB: talent-db-name
      POSTGRES_USER: talent-db-user
      POSTGRES_PASSWORD: talent-db-pwd
      POSTGRES_IP: db
      PORT: 8500
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data: