version: '3.7'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: talent-db-pwd
      POSTGRES_USER: talent-db-user
      POSTGRES_DB: talent-db-name
  talent:
    build:
      context: .
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: 'secret-key'
      DJANGO_SETTINGS_MODULE: core.settings.development
      POSTGRES_DB: talent-db-name
      POSTGRES_USER: talent-db-user
      POSTGRES_PASSWORD: talent-db-pwd
      POSTGRES_IP: db
      PORT: 8000
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data: