version: '3.7'

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      dockerfile: Dockerfile.prod
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      DJANGO_SETTINGS_MODULE: core.settings.production
***REMOVED***
***REMOVED***
***REMOVED***