# Generated by Django 4.2.1 on 2023-05-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='slug',
            field=models.SlugField(default='bru', help_text='Unique address for the testimony.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
