# Generated by Django 4.2.1 on 2023-05-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimony_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestTestimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best', to='testimonials.testimony')),
            ],
        ),
    ]
