# Generated by Django 4.1.9 on 2023-05-25 15:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique address for the testimony.', max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('created', models.DateField(auto_now=True)),
                ('is_open', models.BooleanField(default=True, verbose_name='Open for Applications?')),
                ('application_deadline', models.DateTimeField(verbose_name='When the applications close')),
            ],
        ),
    ]
