# Generated by Django 4.2 on 2023-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlist', '0002_alter_application_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
