# Generated by Django 4.2 on 2023-04-18 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortlist', '0003_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'UNASSIGNED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('COMPLETED', 'COMPLETED')], default='UNASSIGNED', max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='shortlist.application')),
                ('shortlister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'shortlister')},
            },
        ),
    ]
