# Generated by Django 4.2 on 2023-04-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlist', '0006_alter_shortlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'UNASSIGNED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('COMPLETED', 'COMPLETED')], default='UNASSIGNED', max_length=40),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
