# Generated by Django 4.2 on 2023-04-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlist', '0010_rename_reviewed_shortlist_is_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created']},
        ),
    ]
