# Generated by Django 4.2.1 on 2023-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_outlined',
            field=models.BooleanField(default=False),
        ),
    ]
