# Generated by Django 4.2 on 2023-05-04 10:36

import ckeditor.fields
from django.db import migrations, models
import index.models.services


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('thumbnail', models.ImageField(upload_to=index.models.services.image_directory_path)),
            ],
        ),
    ]
