# Generated by Django 4.2 on 2023-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='self-titled', help_text='Unique verbose identifier for the service.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
