# Generated by Django 4.2.1 on 2023-05-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_action_is_outlined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='title',
            field=models.CharField(),
        ),
    ]
