# Generated by Django 4.1.9 on 2023-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
