# Generated by Django 4.2.1 on 2023-05-11 13:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_carouselitem_subtitle_alter_carouselitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='epigraph',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
