# Generated by Django 4.2.1 on 2023-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='epigraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(),
        ),
    ]
