# Generated by Django 4.1.9 on 2023-05-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
