from .registration import RegistrationView
from .login import LoginView
from .reset_password import reset_passwordView
from .dashboard import DashboardView
from .profile.email_change import ChangeEmailView
from .profile.update_personal_info import UpdatePersonalInfoView
from .profile.update_basic_info import UpdateBasicInfoView
from .profile.update_resume import UpdateResumeView
from .profile.update_mode_of_contact import UpdateModeOfContactView
