from .registration import JobSeekerRegistrationView
from .login import LoginView
from .reset_password import ResetPasswordView
from .dashboard import DashboardView
from .profile.email_change import ChangeEmailView
from .profile.update_personal_info import UpdatePersonalInfoView
from .profile.update_basic_info import UpdateBasicInfoView
from .profile.update_resume import UpdateResumeView
from .profile.update_mode_of_contact import UpdateModeOfContactView
from .employer_registration import EmployerRegistrationView
from .profile.employer.update_business_info import UpdateBusinessInfoView
from .staff.registration import StaffRegistrationView
