# Generated by Django 4.1.7 on 2023-04-05 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('length_of_hire', models.IntegerField()),
                ('proposed_remuneration', models.CharField(blank=True, max_length=400, null=True)),
                ('cooperation_type', models.CharField(blank=True, max_length=400, null=True)),
                ('job_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Listing',
            },
        ),
    ]
