# Generated by Django 4.2 on 2023-04-19 13:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
