# Generated by Django 4.1.7 on 2023-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
