# Generated by Django 4.2 on 2023-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
