# Generated by Django 4.1.7 on 2023-04-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_joblisting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='length_of_hire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
