# Generated by Django 4.2 on 2023-04-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobcategory_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobCategory',
            new_name='Industry',
        ),
    ]
