# Generated by Django 4.1.7 on 2023-04-05 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_alter_joblisting_length_of_hire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL),
        ),
    ]
