# Generated by Django 4.2 on 2023-04-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_jobcategory_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='category',
            new_name='industry',
        ),
    ]
