# Generated by Django 4.2 on 2023-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_category_joblisting_industry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['industry'], 'verbose_name_plural': 'Job Listing'},
        ),
        migrations.AddField(
            model_name='joblisting',
            name='city',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='openings',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='length_of_hire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
