# Generated by Django 4.2 on 2023-04-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_joblisting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
