# Generated by Django 4.2.1 on 2023-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='sub_title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(),
        ),
    ]
