# Generated by Django 4.2.1 on 2023-05-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options_alter_partners_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='version',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
