# Generated by Django 4.1.9 on 2023-05-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_sub_title_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='sub_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
